/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ip_packet.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f55cd1bcfb83abbf8b3a31fa0a1c0590)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtl/ip_packet.h>
// pydoc.h is automatically generated in the build directory
#include <ip_packet_pydoc.h>

void bind_ip_packet(py::module& m)
{

    using ip_packet = ::gr::dtl::ip_packet;


    py::class_<ip_packet,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ip_packet>>(m, "ip_packet", D(ip_packet))

        .def(py::init(&ip_packet::make), py::arg("len_key"), D(ip_packet, make))


        ;
}
