/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_adaptive_frame_to_stream_vbb.h) */
/* BINDTOOL_HEADER_FILE_HASH(b53bd091838e7f9640490fbcceeed04a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtl/ofdm_adaptive_frame_to_stream_vbb.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_adaptive_frame_to_stream_vbb_pydoc.h>

void bind_ofdm_adaptive_frame_to_stream_vbb(py::module& m)
{

    using ofdm_adaptive_frame_to_stream_vbb =
        ::gr::dtl::ofdm_adaptive_frame_to_stream_vbb;


    py::class_<ofdm_adaptive_frame_to_stream_vbb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_adaptive_frame_to_stream_vbb>>(
        m, "ofdm_adaptive_frame_to_stream_vbb", D(ofdm_adaptive_frame_to_stream_vbb))

        .def(py::init(&ofdm_adaptive_frame_to_stream_vbb::make),
             py::arg("frame_capacity"),
             py::arg("len_key"),
             D(ofdm_adaptive_frame_to_stream_vbb, make))


        ;
}
