/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_adaptive_stream_to_frame_fvf.h) */
/* BINDTOOL_HEADER_FILE_HASH(0619eeb650db264d8f170d6edce2fdc2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtl/ofdm_adaptive_stream_to_frame_fvf.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_adaptive_stream_to_frame_fvf_pydoc.h>

void bind_ofdm_adaptive_stream_to_frame_fvf(py::module& m)
{

    using ofdm_adaptive_stream_to_frame_fvf =
        ::gr::dtl::ofdm_adaptive_stream_to_frame_fvf;


    py::class_<ofdm_adaptive_stream_to_frame_fvf,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_adaptive_stream_to_frame_fvf>>(
        m, "ofdm_adaptive_stream_to_frame_fvf", D(ofdm_adaptive_stream_to_frame_fvf))

        .def(py::init(&ofdm_adaptive_stream_to_frame_fvf::make),
             py::arg("frame_capacity"),
             py::arg("len_key"),
             D(ofdm_adaptive_stream_to_frame_fvf, make))


        ;
}
