/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_adaptive_constellation_metric_vcvf.h) */
/* BINDTOOL_HEADER_FILE_HASH(f8e53b5b77595242beac84a123217642)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtl/ofdm_adaptive_constellation_metric_vcvf.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_adaptive_constellation_metric_vcvf_pydoc.h>

void bind_ofdm_adaptive_constellation_metric_vcvf(py::module& m)
{

    using ofdm_adaptive_constellation_metric_vcvf =
        ::gr::dtl::ofdm_adaptive_constellation_metric_vcvf;


    py::class_<ofdm_adaptive_constellation_metric_vcvf,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_adaptive_constellation_metric_vcvf>>(
        m,
        "ofdm_adaptive_constellation_metric_vcvf",
        D(ofdm_adaptive_constellation_metric_vcvf))

        .def(py::init(&ofdm_adaptive_constellation_metric_vcvf::make),
             py::arg("fft_len"),
             py::arg("subcarriers"),
             py::arg("constellations"),
             py::arg("len_key"),
             D(ofdm_adaptive_constellation_metric_vcvf, make))


        .def("get_cnst_min_distance",
             &ofdm_adaptive_constellation_metric_vcvf::get_cnst_min_distance,
             py::arg("cnst"),
             D(ofdm_adaptive_constellation_metric_vcvf, get_cnst_min_distance))

        ;
}
