/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_adaptive_equalizer.h) */
/* BINDTOOL_HEADER_FILE_HASH(5c2f5bfd42e956c9f12e2a7f1f7c89e0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtl/ofdm_adaptive_equalizer.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_adaptive_equalizer_pydoc.h>

void bind_ofdm_adaptive_equalizer(py::module& m)
{

    using ofdm_adaptive_equalizer_base = ::gr::dtl::ofdm_adaptive_equalizer_base;
    using ofdm_adaptive_payload_equalizer = ::gr::dtl::ofdm_adaptive_payload_equalizer;
    using ofdm_adaptive_header_equalizer = ::gr::dtl::ofdm_adaptive_header_equalizer;


    py::class_<ofdm_adaptive_equalizer_base,
               gr::digital::ofdm_equalizer_1d_pilots,
               std::shared_ptr<ofdm_adaptive_equalizer_base>>(
        m, "ofdm_adaptive_equalizer_base", D(ofdm_adaptive_equalizer_base))

     //    .def(py::init<int,
     //                  std::shared_ptr<gr::dtl::ofdm_adaptive_frame_snr_base> const,
     //                  std::vector<std::vector<int>> const&,
     //                  std::vector<std::vector<int>> const&,
     //                  std::vector<std::vector<std::complex<float>>> const&,
     //                  int,
     //                  float,
     //                  bool>(),
     //         py::arg("fft_len"),
     //         py::arg("snr_est"),
     //         py::arg("occupied_carriers") = std::vector<std::vector<int>>(),
     //         py::arg("pilot_carriers") = std::vector<std::vector<int>>(),
     //         py::arg("pilot_symbols") = std::vector<std::vector<gr_complex>>(),
     //         py::arg("symbols_skipped") = 0,
     //         py::arg("alpha") = 0.10000000000000001,
     //         py::arg("input_is_shifted") = true,
     //         D(ofdm_adaptive_equalizer_base, ofdm_adaptive_equalizer_base, 0))
     //    .def(py::init<gr::dtl::ofdm_adaptive_equalizer_base const&>(),
     //         py::arg("arg0"),
     //         D(ofdm_adaptive_equalizer_base, ofdm_adaptive_equalizer_base, 1))


        .def("get_snr",
             &ofdm_adaptive_equalizer_base::get_snr,
             D(ofdm_adaptive_equalizer_base, get_snr))


        .def("get_noise",
             &ofdm_adaptive_equalizer_base::get_noise,
             D(ofdm_adaptive_equalizer_base, get_noise))


        .def("equalize",
             (void(ofdm_adaptive_equalizer_base::*)(
                 gr_complex*,
                 int,
                 std::vector<std::complex<float>> const&,
                 std::vector<gr::tag_t> const&)) &
                 ofdm_adaptive_equalizer_base::equalize,
             py::arg("frame"),
             py::arg("n_sym"),
             py::arg("initial_taps") = std::vector<gr_complex>(),
             py::arg("tags") = std::vector<gr::tag_t>(),
             D(ofdm_adaptive_equalizer_base, equalize, 0))


        .def("equalize",
             (void(ofdm_adaptive_equalizer_base::*)(
                 gr_complex*,
                 gr_complex*,
                 int,
                 std::vector<std::complex<float>> const&,
                 std::vector<gr::tag_t> const&)) &
                 ofdm_adaptive_equalizer_base::equalize,
             py::arg("frame"),
             py::arg("frame_soft"),
             py::arg("n_sym"),
             py::arg("initial_taps") = std::vector<gr_complex>(),
             py::arg("tags") = std::vector<gr::tag_t>(),
             D(ofdm_adaptive_equalizer_base, equalize, 1))

        ;


    py::class_<ofdm_adaptive_payload_equalizer,
               gr::dtl::ofdm_adaptive_equalizer_base,
               std::shared_ptr<ofdm_adaptive_payload_equalizer>>(
        m, "ofdm_adaptive_payload_equalizer", D(ofdm_adaptive_payload_equalizer))

        .def(py::init(&ofdm_adaptive_payload_equalizer::make),
             py::arg("fft_len"),
             py::arg("constellations"),
             py::arg("snr_est"),
             py::arg("occupied_carriers") = std::vector<std::vector<int>>(),
             py::arg("pilot_carriers") = std::vector<std::vector<int>>(),
             py::arg("pilot_symbols") = std::vector<std::vector<gr_complex>>(),
             py::arg("symbols_skipped") = 0,
             py::arg("alpha") = 0.10000000000000001,
             py::arg("input_is_shifted") = true,
             D(ofdm_adaptive_payload_equalizer, make))


        .def("equalize",
             &ofdm_adaptive_payload_equalizer::equalize,
             py::arg("frame"),
             py::arg("frame_soft"),
             py::arg("n_sym"),
             py::arg("initial_taps") = std::vector<gr_complex>(),
             py::arg("tags") = std::vector<gr::tag_t>(),
             D(ofdm_adaptive_payload_equalizer, equalize))


        ;


    py::class_<ofdm_adaptive_header_equalizer,
               gr::dtl::ofdm_adaptive_equalizer_base,
               std::shared_ptr<ofdm_adaptive_header_equalizer>>(
        m, "ofdm_adaptive_header_equalizer", D(ofdm_adaptive_header_equalizer))

        .def(py::init(&ofdm_adaptive_header_equalizer::make),
             py::arg("fft_len"),
             py::arg("constellation"),
             py::arg("snr_est"),
             py::arg("occupied_carriers"),
             py::arg("pilot_carriers"),
             py::arg("pilot_symbols"),
             py::arg("symbols_skipped") = 0,
             py::arg("alpha") = 0.10000000000000001,
             py::arg("input_is_shifted") = true,
             D(ofdm_adaptive_header_equalizer, make))


        .def("equalize",
             &ofdm_adaptive_header_equalizer::equalize,
             py::arg("frame"),
             py::arg("frame_soft"),
             py::arg("n_sym"),
             py::arg("initial_taps") = std::vector<gr_complex>(),
             py::arg("tags") = std::vector<gr::tag_t>(),
             D(ofdm_adaptive_header_equalizer, equalize))


        ;
}
