/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_adaptive_constellation_decoder_cb.h) */
/* BINDTOOL_HEADER_FILE_HASH(d8aa6a866b5fdebd4fb9f4c72d397ee2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtl/ofdm_adaptive_constellation_decoder_cb.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_adaptive_constellation_decoder_cb_pydoc.h>

void bind_ofdm_adaptive_constellation_decoder_cb(py::module& m)
{

    using ofdm_adaptive_constellation_decoder_cb =
        ::gr::dtl::ofdm_adaptive_constellation_decoder_cb;


    py::class_<ofdm_adaptive_constellation_decoder_cb,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_adaptive_constellation_decoder_cb>>(
        m,
        "ofdm_adaptive_constellation_decoder_cb",
        D(ofdm_adaptive_constellation_decoder_cb))

        .def(py::init(&ofdm_adaptive_constellation_decoder_cb::make),
             py::arg("constellations"),
             py::arg("tsb_tag_key"),
             D(ofdm_adaptive_constellation_decoder_cb, make))


        ;
}
