/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zmq_msq_pub.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fbd16629ab51b6df155a7d2749320081)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtl/zmq_msq_pub.h>
// pydoc.h is automatically generated in the build directory
#include <zmq_msq_pub_pydoc.h>

void bind_zmq_msq_pub(py::module& m)
{

    using zmq_msq_pub = ::gr::dtl::zmq_msq_pub;


    py::class_<zmq_msq_pub, gr::block, gr::basic_block, std::shared_ptr<zmq_msq_pub>>(
        m, "zmq_msq_pub", D(zmq_msq_pub))

        .def(py::init(&zmq_msq_pub::make),
             py::arg("address"),
             py::arg("bind") = true,
             D(zmq_msq_pub, make))


        ;
}
