"""empty message

Revision ID: c59c44195221
Revises: 
Create Date: 2023-02-20 12:18:59.155252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59c44195221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('pair_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rx_sub_id', sa.String(), nullable=True),
    sa.Column('tx_sub_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pair_id')
    )
    op.create_table('monitor_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pair_id', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('tx_frame_count', sa.Integer(), nullable=True),
    sa.Column('rx_frame_count', sa.Integer(), nullable=True),
    sa.Column('payload_crc_success', sa.Integer(), nullable=True),
    sa.Column('payload_crc_failed', sa.Integer(), nullable=True),
    sa.Column('header_crc_success', sa.Integer(), nullable=True),
    sa.Column('header_crc_failed', sa.Integer(), nullable=True),
    sa.Column('snr_est', sa.Float(), nullable=True),
    sa.Column('current_bps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['subscribers.pair_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor_data')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
